### ISSUE TITLE
Sort an array of 0s, 1s and 2s

### ISSUE THREAD

**Issue by Sahildeep** [Sahildeep/DSA-Hacktoberfest-2022#40]
Given an array consisting of only 0s, 1s and 2s. Write a program to in-place sort the array without using inbuilt sort functions. ( Expected: Single pass-O(N) and constant space)

**Comment by Sajwanankita** [comment]
Please assign this to me.

**Comment by Sahildeep** [comment]
Assigned it to @Sajwanankita
